expensetracker/urls.py
from django.contrib import admin
from django.urls import path
from expense import views
from categories import views as views_categories
from debts import views as views_debts
from loans import views as views_loans
from incomes import views as views_incomes

# ? Lista de obtejos path que define las urls que el proyecto puede manejar y sus correspondientes funciones
urlpatterns = [
    # ? 'path' es una funcion que recibe tres argumentos para definir la ruta/url
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    # ----------LOGIN AND REGISTER----------#
    path('signup/', views.signup, name="signup"),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    # ----------EXPENSES----------#
    path('expense/', views.expense, name='expense'),
    path('expense/create/', views.expense_create, name='expense_create'),
    path('expense/update/<int:expense_id>',
         views.expense_update, name='expense_update'),
    path('expense/update/delete/<int:expense_id>',
         views.expense_delete, name='expense_delete'),
    # ----------CATEGORIES----------#
    path('categories/', views_categories.categories,
         name='categories'),
    path('categories/create/', views_categories.category_create,
         name='category_create'),
    path('chart/expenses-by-category/', views_categories.expenses_by_category_chart,
         name="expenses_by_category_chart"),
    # ----------DEBTS----------#
    path('debts/', views_debts.debts, name="debts"),
    path('debts/create/', views_debts.debts_create, name="debts_create"),
    path('debt/pay/<int:debt_id>', views_debts.debt_pay, name="debt_pay"),
    # ----------LOANS----------#
    path('loans/', views_loans.loans, name="loans"),
    path('loans/create', views_loans.loan_create, name="loans"),
    path('loans/pay/<int:loan_id>', views_loans.loan_pay, name="loan_pay"),
    # ----------INCOMES----------#
    path('incomes/', views_incomes.incomes, name="incomes"),
    path('incomes/create', views_incomes.incomes_create, name="income_create"),
    path('incomes/delete/<int:income_id>',
         views_incomes.income_delete, name='income_delete'),
    path('chart/incomes_by_source/', views_incomes.incomes_by_source_chart,
         name="incomes_by_source_chart"),

]

debts/models.py
from django.db import models
# Importacion del modelo `User` del módulo `models` en el paquete `auth` de Django. 
# Proporciona funcionalidades relacionadas con la autenticación y autorización de usuarios. 
# Contiene campos como nombre de usuario, contraseña, correo electrónico, etc.
from django.contrib.auth.models import User

# Modelo de datos, hereda de la clase las funcionalidades que permite interactuar con la BD
class Debts(models.Model):
    # Campo de llave foranea "user_id" nombre del campo, y el resto es una expresion para los atributos
    user_id = models.ForeignKey(
        # 'User' es la relacion, 'verbose_name' para el admin, 'CASCADE' especifica la eliminacion en cascada
        User, verbose_name="ID del usuario", on_delete=models.CASCADE)
    # Campo de tipo texto/cadena, con longitud maxima de 100 caracteres. 
    debtor_name = models.CharField(
        verbose_name="Nombre del deudor", max_length=100)
    # Campo de tipo texto/cadena pero para textos mas largos, puede ser ilimitada.
    description = models.TextField(
        verbose_name="Descripcion adicional", max_length=500)
    # Campo de tipo decimal, no puede ser vacio, no nulo, max digitos y numero de digitos decimales respectivamente.
    amount = models.DecimalField(
        verbose_name="Monto de la deuda", blank=False, null=False, max_digits=10, decimal_places=2)
    # Campo de tipo fecha y hora, con argumento para establecer fecha y hora actual a la creacion
    date_of_creation = models.DateTimeField(
        verbose_name="Fecha de creaicon", auto_now_add=True)
    
    # Metadatos adicionales
    class Meta:
        db_table = "Deudores"
        verbose_name = "Deudor"
        verbose_name_plural = "Deudores"
    # Método de representacion de cadena que devuelve el nombre del monto, deudor y n. usuario
    def __str__(self) -> str:
        return f"{self.amount} - by {self.debtor_name} - to {self.user_id.username}"

debts/forms.py
from django.forms import ModelForm
from .models import Debts

# Aqui se define la clase (plantilla) para el formulario de la aplicacion
class DebtsForm(ModelForm):
    # La clase Meta en un formulario se utiliza para proporcionar metadatos y configuración adicional
    class Meta:
        model = Debts
        fields = ['debtor_name', 'description', 'amount']

debts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from .models import Debts
from .forms import DebtsForm


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def debts_create(request): # Funcion, de param recibe la solicitud
    if (request.method == "GET"): # Condicional si el metodo de solicitud es 'GET'
        form = DebtsForm() # Instancia del formulario
        return render(request, "debts_create.html", { # Funcion para renderizar la plantilla HTML
            "form": form, # Diccionario con los datos
        })
    else:
        try: # Bloque para manejar excepcion
            form = DebtsForm(request.POST) # Instancia del formulario con la solicitud 'POST'
            newDebts = form.save(commit=False) # Instancia del form antres de guardarse
            newDebts.user_id = request.user # Asignacion del usuario logeado como user_id
            newDebts.save() # Guardadp del formulario
            return redirect("/debts/") # Redireccion al listado de deudas
        except ValueError: # Excepcion en caso de error
            return render(request, "debts_create.html", { #?Renderiza el formulario de crear deuda
                "form": form, # Diccionario con datos
                "eror": "Verifique los datos ingresados" # Dato de error
            })


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def debts(request): # Funcion con solicitud
    debts = Debts.objects.filter(user_id=request.user) # Instancia de los datos que coincidan con el id del user logeado
    return render(request, 'debts.html', { # Renderizacion del listado de deudas
        "debts": debts, # Datos de deudas
    })

@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def debt_pay(request, debt_id): # Funcion que recibe la solicitud y el id de deuda
    try: # Bloque para manejar excepcion
        if request.method == 'GET': # Condicion si la solicitud es 'GET'
            debt = get_object_or_404(Debts, pk=debt_id)# Se obtiene la deuda que su primary key sea igual al id recibido como param
            # De no ser asi se utiliza el methodo 'get_object_or_404' para mandar error 404 not found
            
            form = DebtsForm(instance=debt) # Instancia del formulario con la instanacia de  datos de la deuda
            return render(request, "debt_pay.html", { # Retorno de renderizacion del pago con diccionario
                "debt": debt, # Dato de la deuda
                "form": form, # Formulario
            })
        else: # En caso de no ser 'GET' la solicitud
            debt = get_object_or_404(Debts, pk=debt_id) # Se obtiene la deuda que su primary key sea igual al id recibido como param
            # De no ser asi se utiliza el methodo 'get_object_or_404' para mandar error 404 not found
            
            form = DebtsForm(instance=debt) # Instnaia del form con la instancia de datos de deuda
            newValues = form.save(commit=False)
            amount_pay = Decimal(request.POST["amount_pay"]) # Se extrae el 'amount_pay' del 'POST' que mandamos desde el template
            newValues.amount -= amount_pay # Asignacion decremento del 'amount_pay' a los nuevos valores
            if newValues.amount == 0 or newValues.amount < 0:# Si al restar el abono se liquida o queda negativo, entonces se elimina el deudor
                debt.delete() # Se elimina la deuda
                return redirect("/debts/") # Se redirecciona al listao de deudas
            else: # En caso de no superar o ser igual al valor de la deuda
                newValues.save() # Se guarda la deuda con el 'newValues.amount' restado
                return render(request, "debt_pay.html", { # Retorno de renderizacion de template
                    "debt": debt, # Dato de pago
                    "form": form, # Formulario
                    "success": f"Se ha abonado con exito la cantidad de {amount_pay}" # Mensaje de hecho
                })
    except ValueError: # En caso de excpcion tipo ValueError
        return render(request, "debt_pay.html", { # Renderiza la misma pagina
            "debt": debt, # Con dato de deuda
            "form": form, # Formulario
            "error": "Verifique los datos ingresados" # Pero se manda mensaje de error
        })

debts/templates/debt_pay.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Pago de deudor</h1>
  <section class="form">
    {{ error }}
    {{ success }}
    <form>
      <input
        disabled
        type="number"
        name="amount"
        value="{{ form.instance.amount }}"
        step="0.01"
        required
        id="id_amount"
      />
      <input
        disabled
        type="text"
        name="debtor_name"
        value="{{ form.instance.debtor_name }}"
        maxlength="50"
        required
        id="debtor_name"
      />
    </form>
    <hr />
    <form action="{% url 'debt_pay' debt.id %}" method="POST">
      {% csrf_token %}
      <input
        placeholder="Ingrese monto de abono"
        type="number"
        name="amount_pay"
        step="0.01"
        id="amount_pay"
        required
      />
      <button class="abonar-debt">Restar</button>
    </form>
  </section>
</main>
{% endblock %}

debts/templates/debts.html
{% extends 'base.html' %}

{% block content %}
<main>
  <section class="header">
    <h1 class="title">Deudores</h1>
    <div class="actions">
      <a href="/debts/create/">
        <button>Registrar deudor</button>
      </a>
    </div>
  </section>
  <div class="table-container">
    <table class="expense-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Monto/Dinero</th>
          <th>Fecha de Registro</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for debt in debts %}
        <tr>
          <td>{{ debt.debtor_name }}</td>
          <td>{{ debt.description }}</td>
          <td>${{ debt.amount }}</td>
          <td>{{ debt.date_of_creation }}</td>
          <td>
            <a href="{% url 'debt_pay' debt.id %}">
              <button class="btn-edit abonar">Abonar</button>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

debts/templates/debts_create.html
{% extends 'base.html' %} {% block content %}
<main>
  <section>
    <h1>Registrar deudor</h1>
    {{ error }}
  </section>
  <section class="form">
    <form action="/debts/create/" method="POST">
      {% csrf_token %}
      <input
        placeholder="Nombre del deudor"
        type="text"
        name="debtor_name"
        maxlength="100"
        required
        id="id_debtor_name"
      />
      <textarea
        placeholder="Descripcion"
        name="description"
        cols="40"
        rows="10"
        maxlength="500"
        required
        id="id_description"
      ></textarea>
      <input
        placeholder="Monto de la deuda"
        type="number"
        name="amount"
        step="0.01"
        required
        id="id_amount"
      />
      <button class="btn-form">Registrar</button>
    </form>
  </section>
</main>
{% endblock %}