expensetracker/urls.py
from django.contrib import admin
from django.urls import path
from expense import views
from categories import views as views_categories
from debts import views as views_debts
from loans import views as views_loans
from incomes import views as views_incomes

# ? Lista de obtejos path que define las urls que el proyecto puede manejar y sus correspondientes funciones
urlpatterns = [
    # ? 'path' es una funcion que recibe tres argumentos para definir la ruta/url
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    # ----------LOGIN AND REGISTER----------#
    path('signup/', views.signup, name="signup"),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    # ----------EXPENSES----------#
    path('expense/', views.expense, name='expense'),
    path('expense/create/', views.expense_create, name='expense_create'),
    path('expense/update/<int:expense_id>',
         views.expense_update, name='expense_update'),
    path('expense/update/delete/<int:expense_id>',
         views.expense_delete, name='expense_delete'),
    # ----------CATEGORIES----------#
    path('categories/', views_categories.categories,
         name='categories'),
    path('categories/create/', views_categories.category_create,
         name='category_create'),
    path('chart/expenses-by-category/', views_categories.expenses_by_category_chart,
         name="expenses_by_category_chart"),
    # ----------DEBTS----------#
    path('debts/', views_debts.debts, name="debts"),
    path('debts/create/', views_debts.debts_create, name="debts_create"),
    path('debt/pay/<int:debt_id>', views_debts.debt_pay, name="debt_pay"),
    # ----------LOANS----------#
    path('loans/', views_loans.loans, name="loans"),
    path('loans/create', views_loans.loan_create, name="loans"),
    path('loans/pay/<int:loan_id>', views_loans.loan_pay, name="loan_pay"),
    # ----------INCOMES----------#
    path('incomes/', views_incomes.incomes, name="incomes"),
    path('incomes/create', views_incomes.incomes_create, name="income_create"),
    path('incomes/delete/<int:income_id>',
         views_incomes.income_delete, name='income_delete'),
    path('chart/incomes_by_source/', views_incomes.incomes_by_source_chart,
         name="incomes_by_source_chart"),

]

expense/models.py
from django.db import models
# Importacion del modelo `User` del módulo `models` en el paquete `auth` de Django. 
# Proporciona funcionalidades relacionadas con la autenticación y autorización de usuarios. 
# Contiene campos como nombre de usuario, contraseña, correo electrónico, etc.
from django.contrib.auth.models import User
from categories.models import Category

# Modelo de datos, hereda de la clase las funcionalidades que permite interactuar con la BD
class Expense(models.Model):
    # Campo de llave foranea "user_id" nombre del campo, y el resto es una expresion para los atributos
    user_id = models.ForeignKey(
        # 'User' es la relacion, 'verbose_name' para el admin, 'CASCADE' especifica la eliminacion en cascada
        User, verbose_name="ID del usuario", on_delete=models.CASCADE)
    # Campo de tipo decimal, no puede ser vacio, no nulo, max digitos y numero de digitos decimales respectivamente.
    amount = models.DecimalField(
        verbose_name="Monto del gasto", blank=False, null=False,max_digits=10, decimal_places=2)
    # Campo de tipo texto/cadena, con longitud maxima de 100 caracteres. 
    title = models.CharField(
        verbose_name="Titulo del gasto", blank=False, null=False, max_length=50)
    # Campo de tipo texto/cadena pero para textos mas largos, puede ser ilimitada.
    description = models.TextField(
        verbose_name="Descripcion del monto", blank=True, max_length=500)
    # Campo de tipo llave foranea, al elimnarse la categoria el campo queda como nulo, nulo permitido, respectivamente.
    category_id = models.ForeignKey(
        Category, verbose_name="Categoria del gasto", on_delete=models.SET_NULL, null=True)
    # Campo de tipo fecha y hora, con argumento para establecer fecha y hora actual a la creacion
    date_of_registration = models.DateTimeField(
        verbose_name="Fecha del registro", auto_now_add=True)
    
    # Metadatos adicionales
    class Meta:
        db_table = "Gastos"
        verbose_name = "Gasto"
        verbose_name_plural = "Gastos"
    # Método de representacion de cadena que devuelve el nombre del monto, deudor y n. usuario
    def __str__(self) -> str:
        return f"{self.title} - by {self.user_id.username}"

expense/forms.py
from django.forms import ModelForm
from .models import Expense

# Aqui se define la clase (plantilla) para el formulario de la aplicacion
class ExpenseForm(ModelForm):
    # La clase Meta en un formulario se utiliza para proporcionar metadatos y configuración adicional
    class Meta:
        model = Expense
        fields = ['amount', 'title', 'description', 'category_id',]

expense/views.py
from django.shortcuts import render, redirect, get_object_or_404  # Funciones para renderizar plantillas, redireccionar y obtener objetos o devolver un 404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm  # Formularios de creación y autenticación de usuarios
from django.contrib.auth.models import User  # Modelo de usuario de Django
from django.contrib.auth import login, logout, authenticate  # ?Funciones para iniciar sesión, cerrar sesión y autenticar usuarios
from django.contrib.auth.decorators import login_required  # Decorador para restringir el acceso a usuarios autenticados
from django.db import IntegrityError  # Excepción para manejar errores de integridad en la base de datos
from .forms import ExpenseForm  # Importar formulario personalizado de gastos
from .models import Expense  # Importar el modelo de gastos
from categories.models import Category  # Importar el modelo de categorías

#----------HOME/LANDING----------#

def home(request):
    if request.user.is_authenticated: # Si el usuario está autenticado
        return redirect('/expense/') # redirige al listado de gastos.
    else: # Sino esta autenticado, lo manda a la landing
        return render(request, "home.html")

# ----------LOGIN AND REGISTER----------#


def signup(request): # Funcion para registrarse
    if not request.user.is_authenticated: # Si el usuario está autenticado
        try: # Bloque para manejar excepciones
            if request.method == 'GET': # Condicion para verificar si el metodo de la solicitud es 'GET'
                return render(request, "signup.html", { # Si es 'GET', renderiza el template
                    "form": UserCreationForm # Se le manda el formulario de registro al template
                })
            else: # Sino es 'GET' -> es 'POST'
                if request.POST['password1'] == request.POST['password2']: # Si coinciden las contraseñas
                    try: # Bloque para manejar excepcion
                        user = User.objects.create_user( # Se usa el metodo para crear usuario
                            # Se obtiene el nombre de usuario y la contraseña de la peticion POST
                            username=request.POST["username"], password=request.POST["password1"])
                        login(request, user) # Se inicia sesion con los datos del usuario
                        return redirect('expense') # Se redirecciona a los 'Gastos'
                    # Excepcion que podría ocurrir si se intenta crear un usuario ya existente
                    except IntegrityError: # 'IntegrityError' se produce cuando se viola la integridad de los datos
                        return render(request, "signup.html", { # En caso de excepcion renderizar html
                            "form": UserCreationForm, # Con el formulario de creacion
                            "error": "El usuario ya existe" # Y el error de que ya existe el usuario
                        })
                return render(request, "signup.html", { # En caso de que no se cumpla el if se renderiza el signup
                    "form": UserCreationForm, # Con el formulario de creacion
                    "error": "Las contraseñas no coinciden" # Y el mensaje de que no cinciden las contras
                })
        except ValueError: # En caso de excepcion
            return render(request, "signup.html", { # Se renderiza un error generico
                "form": UserCreationForm,
                "error": "Verifique sus datos"
            })
    else:
         return redirect('/expense/')


def signout(request): # Funcion para cerrar sesion
    logout(request) # Funcion para cerrar sesion, requiere de la peticion como argumento
    return redirect("home") # Redireccion a la pagina de inicio


def signin(request): # Funcion para iniciar sesion
    if request.method == 'GET': # Condicion que evalua si el metodo de la solicitud es 'GET'
        return render(request, "signin.html", { # Si es asi se retorna el template de registro
            "form": AuthenticationForm # Se manda el formulario de registro importado al template
        })
    else:
        user = authenticate( # Se usa el metodo importado para autenticar al usuario, devuelve un objeto o none
            request, # Recibe de argumento la solicitud
            username=request.POST["username"], # Se manda de argumento el username de la solictud 'POST'
            password=request.POST["password"] # Se manda de arg la password de la solictud 'POST'
        )
        if user is None: # Si 'authenticate' no le asigno un obj a 'user', le asigno 'none' pq no existe el usuario
            return render(request, "signin.html", { # Entonces retornamos el template de login/signin
                "form": AuthenticationForm, # Con el formulario de login/signin
                "error": "El usuario o la contraseña es incorrecta" # Mensaje
            })
        else: # Si le devuelve el objeto de usuario 
            login(request, user) # Se inicia sesion con el objeto
            return redirect("/expense") # Se redirecciona a los 'Gastos'

# ----------EXPENSES----------#


# ? Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
@login_required
def expense(request): # Funcion para renderizar los gastos asociados al usuario
    # Se obtienen los datos de laa tabla de gastos donde la llave foranea user_id sea igual al id del usuario logeado
    expenses = Expense.objects.filter(user_id=request.user)
    return render(request, 'expense.html', { # Se renderiza el template
        "expenses": expenses, # Con todos los datos de los gastos del usuario autenticado
    })


# ? Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
@login_required
def expense_create(request): # Funcion para crear gasto
    if request.method == 'GET': # Condicion de si el metodo de la solicitud es 'GET'
        form = ExpenseForm() # Instancia del formulario para crear gasto
        # Del formulario instanciado, en sus campo (field) de categoria se añade una consulta 'queryset'
        form.fields["category_id"].queryset = Category.objects.filter( # se filtran las categorias
            user_id=request.user) # Que pertenecen al usuario, para mostrarse
        return render(request, "expense_create.html", { # Una vez filtrado el fom, se renderiza el html
            'form': form # Y se manda el formulario
        })
    else: # Si la solicitud es 'POST'
        try: # Bloque en caso de excepcion
            form = ExpenseForm(request.POST) # Instancia del formulario con la solicitud 'POST'
            new_expense = form.save(commit=False) # Metodo save para obtener los datos que van a guardarse
            new_expense.user_id = request.user # Se asigna el id del usuario autenticado a la llave foranea 'user_id'
            new_expense.save() # Y ahora si se guarda en la BD
            return redirect("/expense/") # Y se redirecciona a los gastos
        except ValueError: # En caso de error
            return render(request, "expense_create.html", { # Se renderiza la pagina para crear
                'form': ExpenseForm, # Con el formulario
                'error': "Verifique los datos ingresados" # Y un mensaje indicando que hubo un error
            })


# ? Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
@login_required
def expense_update(request, expense_id): # Funcion para actualizar gasto
    if request.method == 'GET': # Si el metodo de la solictud es 'GET'
        # Se obtienen los gastos (o error 404), donde el gasto tenga de llave primaria
        # el id recibido en la solicitud
        expense = get_object_or_404(Expense, pk=expense_id)
        form = ExpenseForm(instance=expense) # Instancia del formulario llenado con la instancia del dato obtenido
        return render(request, "expense_update.html", { # Se retorna el template
            "expense": expense, # Con los datos del gasto obtenido
            "form": form # Y el formulario llenado con el gasto obtenido
        })
    else: # De no ser 'GET'
        # Se obtienen los gastos (o error 404), donde el gasto tenga de llave primaria
        # el id recibido en la solicitud
        expense = get_object_or_404(Expense, pk=expense_id)
        # Instancia del formulario llenado con la instancia del dato obtenido y los datos del 'POST'
        form = ExpenseForm(request.POST, instance=expense)
        form.save() # Se guarda el formulario actualizado
        return redirect("expense") # Se redirecciona a los 'gastos'


# ? Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
@login_required
def expense_delete(request, expense_id): # Funcion para eliminar gasto, recibe id del gasto
    # Se obtienen los datos (o error 404) donde la llave primaria sea el id recibido y 
    # la foranea 'user_id' sea igual al usuario autenticado
    expense = get_object_or_404(Expense, pk=expense_id, user_id=request.user)
    if request.method == "POST": # Si el metodo es 'POST'
        expense.delete() # Se elimina el gasto
        return redirect("/expense/") # Se redirecciona a los gastos

expense/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Administrador Finanzas</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'expenses.css' %}" />
  </head>
  <body>
    <nav>
      <div class="logo">
        <h1>Admin Finanzas</h1>
      </div>
      <ul>
        {% if user.is_authenticated %}
        <li class="nav-expense">
          <a href="/expense">Gastos</a>
        </li>
        <li class="nav-expense">
          <a href="/categories">Categorias</a>
        </li>
        <li class="nav-category-create">
          <a href="/debts/">Deudores</a>
        </li>
        <li class="nav-category-create">
          <a href="/loans/">Prestamos</a>
        </li>
        <li class="nav-category-create">
          <a href="/incomes/">Ingresos</a>
        </li>
        <li class="nav-logout">
          <a href="/logout">Cerrar sesion</a>
        </li>
        {% else %}
        <li class="nav-home">
          <a href="/">Inicio</a>
        </li>
        <li class="nav-signup">
          <a href="/signup">Registrarse</a>
        </li>
        <li class="nav-signin">
          <a href="/signin">Iniciar sesion</a>
        </li>
        {% endif %}
      </ul>
      <div class="hamburger">
        <span class="line"></span>
        <span class="line"></span>
        <span class="line"></span>
      </div>
    </nav>
    <div class="menubar">
      <ul>
        {% if user.is_authenticated %}
        <li class="nav-expense">
          <a href="/expense">Gastos</a>
        </li>
        <li class="nav-expense">
          <a href="/categories">Categorias</a>
        </li>
        <li class="nav-category-create">
          <a href="/debts/">Deudores</a>
        </li>
        <li class="nav-category-create">
          <a href="/loans/">Prestamos</a>
        </li>
        <li class="nav-category-create">
          <a href="/incomes/">Ingresos</a>
        </li>
        <li class="nav-logout">
          <a href="/logout">Cerrar sesion</a>
        </li>
        {% else %}
        <li class="nav-home">
          <a href="/">Inicio</a>
        </li>
        <li class="nav-signup">
          <a href="/signup">Registrarse</a>
        </li>
        <li class="nav-signin">
          <a href="/signin">Iniciar sesion</a>
        </li>
        {% endif %}
      </ul>
    </div>

    <script src="{% static 'script.js' %}"></script>
    {% block content %}
    <!-- CONTENIDO DE LAS APPS -->
    {% endblock %}
  </body>
</html>

expense/templates/create_expense.html
{% extends "base.html" %} 
{% block content %} 

<h1>Create expense</h1>
{{error}}
<form action="/expense/create/" method="POST">
  {% csrf_token %} 
  {{ form }}
  <button>Guardar</button>
</form>

{% endblock %}

expense/templates/expense.html
{% extends "base.html" %} {% block content %}
<main>
  <section class="header">
    <h1 class="title">Gastos</h1>
    <div class="actions">
      <a href="/expense/create">
        <button>Registrar gasto</button>
      </a>
      <a href="/categories/create/">
        <button>Crear categoria</button>
      </a>
      <a href="/chart/expenses-by-category/">
        <button>Grafica de gastos por categoria</button>
      </a>
    </div>
  </section>
  <div class="table-container">
    <table class="expense-table">
      <thead>
        <tr>
          <th>Monto</th>
          <th>Descripción</th>
          <th>Categoría</th>
          <th>Fecha de Registro</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in expenses %}
        <tr>
          <td>${{ expense.amount }}</td>
          <td>{{ expense.title }}</td>
          <td>{{ expense.category_id.name }}</td>
          <td>{{ expense.date_of_registration }}</td>
          <td>
            <a href="{% url 'expense_update' expense.id %}">
              <button class="btn-edit editar">Editar</button>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

expense/templates/expense_create.html
{% extends "base.html" %} 

{% block content %}
<main>
  <section>
    <h1>Crear gasto</h1>
    {{error}}
  </section>
  <section class="form">
    <form action="/expense/create/" method="POST">
      {% csrf_token %}
      <input placeholder="Monto/Precio" type="number" name="amount" step="0.01" required id="id_amount">
      <input placeholder="Titulo" type="text" name="title" maxlength="50" required id="id_title">
      <textarea placeholder="Descripcion" name="description" cols="40" rows="10" maxlength="500" id="id_description"></textarea>
      <div> 
        Categoria: {{ form.category_id }}
       </div>
       <button class="btn-form">Guardar</button>
    </form>
  </section>
</main>
{% endblock %}

expense/templates/expense_update.html
{% extends "base.html" %}
{% block content %}
  <main>
    <h1>Detalles del gasto</h1>
    <section class="form">
      <form method="POST">
        {% csrf_token %}
        <input type="number" name="amount" value="{{ form.instance.amount }}" step="0.01" required id="id_amount">
        <input type="text" name="title" value="{{ form.instance.title }}" maxlength="50" required id="id_title">
        <textarea name="description" cols="40" rows="10" maxlength="500" id="id_description">{{ form.instance.description }}</textarea>
        <div>
          Categoria del gasto: {{ form.category_id }}
        </div>
        <button class="btn-form">Actualizar</button>
      </form>
      <form action="{% url 'expense_delete' expense.id %}" method="POST">
        {% csrf_token %}
        <button class="btn-form eliminar">Eliminar</button>
      </form>
    </section>
  </main>
{% endblock %}

expense/templates/home.html
<main class="home-main">
  <div class="container">
    <section class="home-section-text">
      <h1 class="home-h1">Registro de Gastos diarios</h1>
      <h1 class="home-h1">controla tus finanzas</h1>
        <p class="home-p">
          Registra tus gastos diarios y lleva un control de tus finanzas de manera
          fácil y rápida.
          Rregistra tus gastos y mantener un seguimiento
          detallado de tus finanzas.
        </p>
    </section>
    <section class="home-section-buttons">
      <a class="home-archor" href="/signin">
        <button class="home-signin">Iniciar Sesión</button>
      </a>
      <a class="home-archor" href="/signup">
        <button class="home-signup">Registrarse</button>
      </a>
    </section>
  </div>
</main>

<style>
  body {
    margin: 0;
    font-family: "Arial", "Helvetica", sans-serif;
  }

  .home-main {
    height: 100vh;
    background-color: white;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .container {
    display: flex;
    flex-direction: column;
    width: 50%;
    gap: 2rem;
  }

  .home-section-text {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 1rem;
  }

  .home-section-text * {
    margin: 0;
  }

  .home-h1 {
    font-size: 3rem; /* Tamaño de texto */
    background: linear-gradient(to right, #b927fc 0%, #2c64fc 100%); /* Gradiente de fondo */
    background-clip: text; /* Clip de fondo del texto */
    color: transparent; /* Color del texto transparente */
  }

  .home-p {
    width: 80%;
    font-size: larger;
    color: white;
    text-align: center;
  }

  .home-signup {
    background-color: white;
  }

  .home-signin {
    background-color: white;
  }

  .home-section-buttons {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 2rem;
  }

  button {
    font-size: larger;
    color: white;
    width: 200px;
    height: 50px;
    border-radius: 15px;
    border: none;
    cursor: pointer;
  }

  .home-signin {
    background: #15C39A;
  }

  .home-signin:hover {
    background-color: #041046;
    transition: 0.2s;
  }

  .home-signup {
    background-color: #3157ff; 
  }

  .home-signup:hover {
    background-color: #041046;
    transition: 0.2s;
  }
</style>

expense/templates/signin.html
{% extends 'base.html' %} {% block content %}
<main>
  <h1 class="title-login">Iniciar sesion</h1>
    {{error}}
  <section class="form" class="container-form">
    <form action="/signin/" method="POST">
      {% csrf_token %}
      <input
        id="id_username"
        name="username"
        type="text"
        placeholder="Nombre de usuario"
      />
      <input
        id="id_password"
        name="password"
        type="password"
        placeholder="Contraseña"
      />
      <button class="btn-form">Iniciar sesion</button>
    </form>
  </section>
</main>
{% endblock %}

expense/templates/signup.html
{% extends 'base.html' %} {% block content %}
<main>
  <section>
    <h1>Registrarse</h1>
    {{error}}
  </section>
  <section class="form">
    <form id="form_signup" action="/signup/" method="POST">
      {% csrf_token %}
      <!-- {{form.as_p}} -->
      <input
        id="id_username"
        name="username"
        type="text"
        placeholder="Nombre de usuario"
      />
      <input
        id="id_password1"
        name="password1"
        type="password"
        placeholder="Contraseña"
      />
      <input
        id="id_password2"
        name="password2"
        type="password"
        placeholder="Ingrese de nuevo la contraseña"
      />
      <button id="btn-signup" class="btn-form">Registrarse</button>
    </form>
  </section>
</main>

{% endblock %}