expensetracker/urls.py
from django.contrib import admin
from django.urls import path
from expense import views
from categories import views as views_categories
from debts import views as views_debts
from loans import views as views_loans
from incomes import views as views_incomes

# ? Lista de obtejos path que define las urls que el proyecto puede manejar y sus correspondientes funciones
urlpatterns = [
    # ? 'path' es una funcion que recibe tres argumentos para definir la ruta/url
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    # ----------LOGIN AND REGISTER----------#
    path('signup/', views.signup, name="signup"),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    # ----------EXPENSES----------#
    path('expense/', views.expense, name='expense'),
    path('expense/create/', views.expense_create, name='expense_create'),
    path('expense/update/<int:expense_id>',
         views.expense_update, name='expense_update'),
    path('expense/update/delete/<int:expense_id>',
         views.expense_delete, name='expense_delete'),
    # ----------CATEGORIES----------#
    path('categories/', views_categories.categories,
         name='categories'),
    path('categories/create/', views_categories.category_create,
         name='category_create'),
    path('chart/expenses-by-category/', views_categories.expenses_by_category_chart,
         name="expenses_by_category_chart"),
    # ----------DEBTS----------#
    path('debts/', views_debts.debts, name="debts"),
    path('debts/create/', views_debts.debts_create, name="debts_create"),
    path('debt/pay/<int:debt_id>', views_debts.debt_pay, name="debt_pay"),
    # ----------LOANS----------#
    path('loans/', views_loans.loans, name="loans"),
    path('loans/create', views_loans.loan_create, name="loans"),
    path('loans/pay/<int:loan_id>', views_loans.loan_pay, name="loan_pay"),
    # ----------INCOMES----------#
    path('incomes/', views_incomes.incomes, name="incomes"),
    path('incomes/create', views_incomes.incomes_create, name="income_create"),
    path('incomes/delete/<int:income_id>',
         views_incomes.income_delete, name='income_delete'),
    path('chart/incomes_by_source/', views_incomes.incomes_by_source_chart,
         name="incomes_by_source_chart"),

]

incomes/models.py
from django.db import models
# Importacion del modelo `User` del módulo `models` en el paquete `auth` de Django. 
# Proporciona funcionalidades relacionadas con la autenticación y autorización de usuarios. 
# Contiene campos como nombre de usuario, contraseña, correo electrónico, etc.
from django.contrib.auth.models import User

# Modelo de datos, hereda de la clase las funcionalidades que permite interactuar con la BD
class Incomes(models.Model):
    # Campo de llave foranea "user_id" nombre del campo, y el resto es una expresion para los atributos
    user_id = models.ForeignKey(
        # 'User' es la relacion, 'verbose_name' para el admin, 'CASCADE' especifica la eliminacion en cascada
        User, verbose_name="ID del usuairo", on_delete=models.CASCADE)
    # Campo de tipo decimal, no puede ser vacio, no nulo, max digitos y numero de digitos decimales respectivamente.
    amount = models.DecimalField(
        verbose_name="Monto del ingreso", blank=False, null=False, max_digits=10, decimal_places=2)
    # Campo de tipo texto/cadena, campo no permite estar vacio, con longitud maxima de 50 caracteres. 
    source = models.CharField(
        verbose_name="Fuente de ingreso", blank=False, max_length=50)
    # Campo de tipo texto/cadena pero para textos mas largos, puede ser ilimitada.
    description = models.TextField(
        verbose_name="Descripcion del prestamo", blank=True, max_length=500)
    # Campo de tipo fecha y hora, con argumento para establecer fecha y hora actual a la creacion
    date_of_registration = models.DateTimeField(
        verbose_name="Fecha del registro", auto_now_add=True)

    # Metadatos adicionales
    class Meta:
        db_table = "Ingresos"
        verbose_name = "Ingreso"
        verbose_name_plural = "Ingresos"
    # Método de representacion de cadena que devuelve el nombre del monto, deudor y n. usuario
    def __str__(self) -> str:
        return f"You earned ${self.amount} from {self.source}"

incomes/views.py
from django.shortcuts import render, redirect, get_object_or_404 # Funciones para renderizar plantillas, redireccionar y obtener objetos o devolver un 404
from django.contrib.auth.decorators import login_required # Decorador para restringir el acceso a usuarios autenticados
from .models import Incomes # Modelo de los ingresos
from .form import IncomesForm # Formulario de los ingresos
import json # Metodo para convertir en JSON


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def incomes(request): # Funcion para mostrar los ingresos
    incomes = Incomes.objects.filter(user_id=request.user) # Se obtienen los datos que tengan relacion con el usuario autenticado
    return render(request, "incomes.html", { # Se renderiza el listado de ingresos
        'incomes': incomes # Se mandan los datos
    })


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def incomes_create(request): # Funcion para crear ingresos
    if request.method == 'GET': # Si el metodo es 'GET'
        form = IncomesForm() # Se instancia el formulario
        return render(request, "income_create.html", { # Se renderiza el formulario en el template
            "form": form, # Datos
        })
    else: # Sino es 'GET'
        try: # Bloque manejador de excepciones
            form = IncomesForm(request.POST) # Instancia del formulario con los datos 'POST'
            newIncome = form.save(commit=False) # Se guardan los datos antes de ser guardados
            newIncome.user_id = request.user # Se asigna el id del usuario auth al fk 'user_id'
            newIncome.save() # Se guarda el formulario
            return redirect("/incomes/") # Se redirecciona al listado
        except ValueError: # En caso de error
            return render(request, "income_create.html", { # Se retorna la renderizacion del template
                "form": form, # Con el formulario
                "error": "Verifique los datos ingresados" # Y el msj de error
            })


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def incomes_by_source_chart(request): # Funcion para la grafica de ingresos
    incomes = Incomes.objects.filter(user_id=request.user) # Ingresos que sean del usuario autenticado
    income_sum_by_source = {}  # Diccionario para almacenar la suma de ingresos por fuente
    # Calcular la suma de ingresos por fuente
    for income in incomes:  # Itera por cada ingreso en la lista incomes
        if income.source in income_sum_by_source:  # Si la fuente del ingreso está en el diccionario income_sum_by_source
            # Asigna-adiciona el monto del ingreso al valor existente en income_sum_by_source para la fuente correspondiente
            income_sum_by_source[income.source] += income.amount
        else:
            # Si la fuente del ingreso no se encuentra en el diccionario, agrega una nueva entrada con el monto del ingreso actual
            income_sum_by_source[income.source] = income.amount
            
    # Preparar los datos en el formato necesario para el gráfico
    # Cada elemento del diccionario se convierte en un diccionario en la lista 'data', donde:
    # - La clave 'source' corresponde a la fuente del ingreso.
    # - La clave 'amount' corresponde a la cantidad de ingresos, convertida a tipo flotante.
    data = [{"source": source, "amount": float(amount)} 
    # Se itera sobre los elementos del diccionario 'income_sum_by_source' para formatear los datos.
            for source, amount in income_sum_by_source.items()]
    print(data) #? Aqui imprimí para visualizar los datos y corroborar que estuvieran bien
    return render(request, "incomes_by_source_chart.html", { # Se renderiza la grafica
        "data": json.dumps(data)  # Se mandan los datos como un JSON
    })


@login_required # Decorador para proteger ruta / Acceso a la vista solo a usuarios autenticados
def income_delete(request, income_id): # Funcion para eliminar el ingreso, recibe el id del ingreso a eliminar
    # Se obtiene el ingreso donde la primary key es el id recibido y el foreign key es el id del usuario auth
    income = get_object_or_404(Incomes, pk=income_id, user_id=request.user)
    if request.method == "POST": # Si el metodo de la solicitud es 'POST'
        income.delete() # Se elimina el ingreso
        return redirect("/incomes/") # Se redirecciona al listado

incomes/templates/income_create.html
{% extends "base.html" %} {% block content %}
<main>
  <section>
    <h1>Registrar ingreso</h1>
    {{error}}
  </section>
  <section>
    <form class="form" action="/incomes/create" method="POST">
      {% csrf_token %}
      <input
        placeholder="Nombre de la fuente de ingreso"
        type="text"
        name="source"
        maxlength="50"
        required
        id="id_source"
      />
      <input
        placeholder="Monto de ingreso"
        type="number"
        name="amount"
        step="0.01"
        required
        id="id_amount"
      />
      <textarea
        name="description"
        cols="40"
        rows="10"
        maxlength="500"
        id="id_description"
      ></textarea>
      <button class="btn-form">Guardar</button>
    </form>
  </section>
</main>
{% endblock %}

incomes/templates/incomes.html
{% extends 'base.html' %} 

{% block content %}
<main>
  <section class="header">
    <h1 class="title">Ingresos</h1>
    <div class="actions">
      <a href="/incomes/create">
        <button>Registrar ingreso</button>
      </a>
      <a href="/chart/incomes_by_source/">
        <button>Grafica ingresos por fuente</button>
      </a>
    </div>
  </section>
  <div class="table-container">
    <table class="expense-table">
      <thead>
        <tr>
          <th>Fuente de ingreso</th>
          <th>Descripcion</th>
          <th>Monto/Dinero</th>
          <th>Fecha de Registro</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for income in incomes %}
        <tr>
          <td>{{ income.source }}</td>
          <td>{{ income.description }}</td>
          <td>{{ income.amount }}</td>
          <td>{{ income.date_of_registration }}</td>
          <td>
            <a>
              <form action="{% url 'income_delete' income.id %}" method="POST">
                {% csrf_token %}
                <button class="eliminar">Eliminar</button>
              </form>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

incomes/templates/incomes_by_source_chart.html
{% extends 'base.html' %}

{% block content %}
<main>
  <h1>Ingresos totales por fuente de ingreso</h1>
  <section class="chart">
    <canvas id="myChart"></canvas>
  </section>
</main>

<style>
  .chart{
    width: 50vw;
  }
</style>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');
  //'safe' es un filtro de plantilla que se utiliza para marcar una cadena como "segura"
  // Lo que sinifica que tiene un formato correcto y no es codigo malicioso
  const dataFromDjango = '{{ data | safe }}';
  const dataParsed = JSON.parse(dataFromDjango)
  labels = dataParsed.map(_data => _data.source);
  totals = dataParsed.map(_data => _data.amount);

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: labels,
      datasets: [{
        label: 'Pesos',
        data: totals,
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>
{% endblock %}