expensetracker/urls.py
from django.contrib import admin
from django.urls import path
from expense import views
from categories import views as views_categories
from debts import views as views_debts
from loans import views as views_loans
from incomes import views as views_incomes

# ? Lista de obtejos path que define las urls que el proyecto puede manejar y sus correspondientes funciones
urlpatterns = [
    # ? 'path' es una funcion que recibe tres argumentos para definir la ruta/url
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    # ----------LOGIN AND REGISTER----------#
    path('signup/', views.signup, name="signup"),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    # ----------EXPENSES----------#
    path('expense/', views.expense, name='expense'),
    path('expense/create/', views.expense_create, name='expense_create'),
    path('expense/update/<int:expense_id>',
         views.expense_update, name='expense_update'),
    path('expense/update/delete/<int:expense_id>',
         views.expense_delete, name='expense_delete'),
    # ----------CATEGORIES----------#
    path('categories/', views_categories.categories,
         name='categories'),
    path('categories/create/', views_categories.category_create,
         name='category_create'),
    path('chart/expenses-by-category/', views_categories.expenses_by_category_chart,
         name="expenses_by_category_chart"),
    # ----------DEBTS----------#
    path('debts/', views_debts.debts, name="debts"),
    path('debts/create/', views_debts.debts_create, name="debts_create"),
    path('debt/pay/<int:debt_id>', views_debts.debt_pay, name="debt_pay"),
    # ----------LOANS----------#
    path('loans/', views_loans.loans, name="loans"),
    path('loans/create', views_loans.loan_create, name="loans"),
    path('loans/pay/<int:loan_id>', views_loans.loan_pay, name="loan_pay"),
    # ----------INCOMES----------#
    path('incomes/', views_incomes.incomes, name="incomes"),
    path('incomes/create', views_incomes.incomes_create, name="income_create"),
    path('incomes/delete/<int:income_id>',
         views_incomes.income_delete, name='income_delete'),
    path('chart/incomes_by_source/', views_incomes.incomes_by_source_chart,
         name="incomes_by_source_chart"),

]

loans/models.py
from django.db import models
# Importacion del modelo `User` del módulo `models` en el paquete `auth` de Django. 
# Proporciona funcionalidades relacionadas con la autenticación y autorización de usuarios. 
# Contiene campos como nombre de usuario, contraseña, correo electrónico, etc.
from django.contrib.auth.models import User

# Create your models here.

# Modelo de datos, hereda de la clase las funcionalidades que permite interactuar con la BD
class Loans(models.Model):
    # Campo de llave foranea "user_id" nombre del campo, y el resto es una expresion para los atributos
    user_id = models.ForeignKey(
        # 'User' es la relacion, 'verbose_name' para el admin, 'CASCADE' especifica la eliminacion en cascada
        User, verbose_name="ID del usuairo", on_delete=models.CASCADE)
    # Campo de tipo texto/cadena, con longitud maxima de 100 caracteres. 
    lender = models.CharField(
        verbose_name="Prestamista", blank=False, null=False, max_length=50)
    # Campo de tipo decimal, no puede ser vacio, no nulo, max digitos y numero de digitos decimales respectivamente.
    amount = models.DecimalField(
        verbose_name="Monto del prestamo", blank=False, null=False, max_digits=10, decimal_places=2)
    # Campo de tipo texto/cadena pero para textos mas largos, puede ser ilimitada.
    description = models.TextField(
        verbose_name="Descripcion del prestamo", blank=True, max_length=500)
    # Campo de tipo fecha y hora, con argumento para establecer fecha y hora actual a la creacion
    date_of_registration = models.DateTimeField(
        verbose_name="Fecha del registro", auto_now_add=True)
    
    # Metadatos adicionales
    class Meta:
        db_table = "Prestamos"
        verbose_name = "Prestamo"
        verbose_name_plural = "Prestamos"
    # Método de representacion de cadena que devuelve el nombre del monto, deudor y n. usuario
    def __str__(self) -> str:
        return f"You owne ${self.amount} to {self.lender}"

loans/views.py
from django.shortcuts import render, redirect, get_object_or_404  # Funciones para renderizar plantillas, redireccionar y obtener objetos o devolver un 404
from django.contrib.auth.decorators import login_required  # Decorador para restringir el acceso a usuarios autenticados
from decimal import Decimal  # Para trabajar con numeros decimales
from .models import Loans  # Importacion del modelo de prestamos
from .form import LoansForm  # Importacion del formulario de prestamos


@login_required  # Acceso a la vista solo a usuarios autenticados
def loans(request):  # Funcion para mostrar los prestamos
    loans = Loans.objects.filter(user_id=request.user)  # Se obtienen los prestamos relacionados con el usuario autenticado
    return render(request, "loans.html", {  # Se renderiza el listado de prestamos
        'loans': loans  # Se envian los datos
    })


@login_required  # Acceso a la vista solo a usuarios autenticados
def loan_create(request):  # Funcion para crear prestamos
    if request.method == 'GET':  # Si el metodo es 'GET'
        form = LoansForm()  # Se instancia el formulario
        return render(request, "loan_create.html", {  # Se renderiza el formulario en el template
            "form": form,  # Se envian los datos
        })
    else:  # Sino es 'GET'
        try:  # Bloque manejador de excepciones
            form = LoansForm(request.POST)  # Instancia del formulario con los datos 'POST'
            newLoan = form.save(commit=False)  # Se guardan los datos antes de ser guardados
            newLoan.user_id = request.user  # Se asigna el id del usuario autenticado al fk 'user_id'
            newLoan.save()  # Se guarda el formulario
            return redirect("/loans")  # Se redirecciona al listado
        except ValueError:  # En caso de error
            return render(request, "loan_create.html", {  # Se retorna la renderización del template
                "form": form,  # Con el formulario
                "error": "Verifique los datos ingresados"  # Y el mensaje de error
            })


@login_required  # Acceso a la vista solo a usuarios autenticados
def loan_pay(request, loan_id):  # Funcion para realizar pagos de prestamos, recibe el id del prestamo a pagar
    try:  # Bloque manejador de excepciones
        if request.method == 'GET':  # Si el metodo de la solicitud es 'GET'
            loan = get_object_or_404(Loans, pk=loan_id)  # Se obtiene el prestamo con la primary key recibida
            form = LoansForm(instance=loan)  # Se instancia el formulario con la instancia del prestamo
            return render(request, "loan_pay.html", {  # Se renderiza la pagina de pago del prestamo
                "loan": loan,  # Se envia el prestamo
                "form": form,  # Y el formulario
            })
        else:  # Si no es 'GET'
            loan = get_object_or_404(Loans, pk=loan_id)  # Se obtiene el prestamo con la primary key recibida
            form = LoansForm(instance=loan)  # Se instancia el formulario con la instancia del prestamo
            newValues = form.save(commit=False)  # Se guardan los nuevos valores antes de guardarlos
            # Se extrae el valor del pago del prestamo desde el formulario
            amount_pay = Decimal(request.POST["amount_pay"])
            newValues.amount -= amount_pay  # Se resta el pago al total del prestamo
            # Si el prestamo se liquida o queda con saldo negativo, se elimina
            if newValues.amount == 0 or newValues.amount < 0:
                loan.delete()  # Se elimina el prestamo
                return redirect("/loans/")  # Se redirecciona al listado de prestamos
            else:  # Si no se liquida completamente
                newValues.save()  # Se guardan los nuevos valores
                return render(request, "loan_pay.html", {  # Se renderiza la pagina de pago del prestamo
                    "loan": loan,  # Se envia el prestamo
                    "form": form,  # El formulario
                    "success": f"Se ha abonado con éxito la cantidad de {amount_pay}"  # Y un mensaje de éxito
                })
    except ValueError:  # En caso de error
        return render(request, "loan_pay.html", {  # Se renderiza la pagina de pago del prestamo
            "loan": loan,  # Se envia el prestamo
            "form": form,  # El formulario
            "error": "Verifique los datos ingresados"  # Y un mensaje de error
        })

loans/templates/loan_create.html
{% extends "base.html" %} {% block content %}
<main>
  <section>
    <h1>Registra prestamo</h1>
    {{error}}
  </section>
  <section class="form">
    <form action="/loans/create" method="POST">
      {% csrf_token %}
      <input
        placeholder="Prestamista"
        type="text"
        name="lender"
        maxlength="50"
        required
        id="id_lender"
      />
      <input
        placeholder="Monto"
        type="number"
        name="amount"
        step="0.01"
        required
        id="id_amount"
      />
      <textarea
        placeholder="Description"
        name="description"
        cols="40"
        rows="10"
        maxlength="500"
        id="id_description"
      ></textarea>
      <button class="btn-form">Guardar</button>
    </form>
  </section>
</main>
{% endblock %}

loans/templates/loan_pay.html
{% extends "base.html" %} {% block content %}
<main>
  <h1>Pago de prestamo</h1>
  {{ error }} 
  {{ success }}
  <section class="form">
    <form>
      <input
        disabled
        type="number"
        name="amount"
        value="{{ form.instance.amount }}"
        step="0.01"
        required
        id="id_amount"
      />
      <input
        disabled
        type="text"
        name="lender"
        value="{{ form.instance.lender }}"
        maxlength="50"
        required
        id="id_lender"
      />
    </form>
    <hr />
    <form action="{% url 'loan_pay' loan.id %}" method="POST">
      {% csrf_token %}
      <input
        placeholder="Ingrese monto de abono"
        type="number"
        name="amount_pay"
        step="0.01"
        id="amount_pay"
        required
      />
      <button>Restar</button>
    </form>
  </section>
</main>
{% endblock %}

loans/templates/loans.html
{% extends 'base.html' %} 

{% block content %}
<main>
  <section class="header">
    <h1 class="title">Prestamos</h1>
    <div class="actions">
      <a href="/loans/create">
        <button>Registrar prestamo</button>
      </a>
    </div>
  </section>
  <div class="table-container">
    <table class="expense-table">
      <thead>
        <tr>
          <th>Prestamista</th>
          <th>Descripcion</th>
          <th>Monto/Dinero</th>
          <th>Fecha de Registro</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for loan in loans %}
        <tr>
          <td>{{ loan.lender }}</td>
          <td>{{ loan.description }}</td>
          <td>{{ loan.amount }}</td>
          <td>{{ loan.date_of_registration }}</td>
          <td>
            <a href="{% url 'loan_pay' loan.id %}">
              <button class="btn-edit abonar">Abonar</button>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}